apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alterconso.fullname" . }}
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
data:
  config.yaml: |
    db_host: {{ include "alterconso.dbHost" . | quote }}
    db_port: {{ include "alterconso.dbPort" . | quote }}
    {{- toYaml .Values.config | nindent 4 }}
