{{- if .Values.database.embedded.enabled }}
{{- $mysqlName := printf "%s-mysql" (include "alterconso.fullname" .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $mysqlName }}
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  clusterIP: None # Headless Service, requis par les StatefulSets
  ports:
    - port: 3306
      targetPort: mysql
      name: mysql
  selector:
    app: {{ $mysqlName }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $mysqlName }}
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ $mysqlName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ $mysqlName }}
  template:
    metadata:
      labels:
        app: {{ $mysqlName }}
        {{- include "alterconso.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mysql
          image: "mysql:{{ .Values.database.embedded.version }}"
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "alterconso.secretName" . }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.config.db_name | quote }}
            - name: MYSQL_USER
              value: {{ .Values.config.db_user | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "alterconso.secretName" . }}
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.database.embedded.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        {{- with .Values.database.embedded.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.embedded.persistence.size }}
{{- end }}
