{{- /*
Le chart ne crée le Secret QUE si l'utilisateur n'a pas pointé un Secret
externe (existingSecret = pattern SOPS / SealedSecrets / ESO).
*/}}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alterconso.fullname" . }}
  labels:
    {{- include "alterconso.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k := (omit .Values.secrets "existingSecret") | keys | sortAlpha }}
  {{ $k }}: {{ index $.Values.secrets $k | quote }}
  {{- end }}
{{- end }}
